import { useState } from 'react';
import { ArrowLeft, ArrowDown, ArrowUp, FileText, Loader2, RotateCw, Trash2, Upload } from 'lucide-react';
import { Link } from 'react-router-dom';
import { fileService } from '../services/api.js';

export default function OrganizePdfPage() {
 const [file,setFile]=useState<File|null>(null); const [count,setCount]=useState(0); const [order,setOrder]=useState('');
 const [deleted,setDeleted]=useState<number[]>([]); const [rotations,setRotations]=useState<Record<number,number>>({});
 const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const load=async(f:File|null)=>{setFile(f);setCount(0);setDeleted([]);setRotations({});setError('');setOrder('');if(!f)return;try{const d=await fileService.getPdfInfo(f);setCount(d.page_count);setOrder(Array.from({length:d.page_count},(_,i)=>i+1).join(', '));}catch(e:any){setError(fileService.getApiErrorMessage(e));setFile(null);}};
 const process=async()=>{if(!file)return;setLoading(true);setError('');try{const nums=order.split(',').map(v=>Number(v.trim())).filter(Boolean);const blob=await fileService.organizePdf(file,nums,rotations,deleted);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${file.name.replace(/\.pdf$/i,'')}-organized.pdf`;a.click();URL.revokeObjectURL(url);}catch(e:any){setError(fileService.getApiErrorMessage(e,'Could not organize PDF.'));}finally{setLoading(false);}};
 const toggleDelete=(n:number)=>{
   if(deleted.includes(n)){setDeleted(prev=>prev.filter(x=>x!==n));setOrder(prev=>{const nums=prev.split(',').map(v=>Number(v.trim())).filter(Boolean);return [...nums,n].join(', ');});}
   else{setDeleted(prev=>[...prev,n]);setOrder(prev=>prev.split(',').map(v=>Number(v.trim())).filter(x=>x&&x!==n).join(', '));}
 };
 return <div className="min-h-screen bg-[#F8FAFC] py-12 sm:py-16 text-[#1E293B]"><div className="max-w-4xl mx-auto px-4 space-y-8"><Link to="/tools" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-blue-600"><ArrowLeft size={16}/> Back to All Tools</Link>
 <header className="space-y-3"><div className="inline-flex items-center gap-2 rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-700">PDF WORKSPACE</div><h1 className="text-3xl sm:text-4xl font-extrabold">Organize PDF</h1><p className="text-slate-500">Reorder pages, rotate individual pages, remove unwanted pages, or combine files using Merge PDF.</p></header>
 <section className="rounded-3xl border border-slate-200 bg-white p-5 sm:p-8 space-y-6 shadow-sm"><label className="flex min-h-32 cursor-pointer flex-col items-center justify-center gap-3 rounded-2xl border-2 border-dashed border-slate-200 bg-slate-50 p-5 text-center hover:border-blue-300"><Upload className="text-blue-600" size={26}/><span className="font-semibold">{file?file.name:'Select a PDF file'}</span><span className="text-xs text-slate-500">PDF only · up to 50 MB</span><input type="file" accept="application/pdf,.pdf" className="hidden" onChange={e=>load(e.target.files?.[0]||null)}/></label>
 {count>0&&<><div className="rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{count} pages detected. Page numbers are one-based.</div><div className="space-y-2"><label className="text-sm font-semibold">New page order</label><input value={order} onChange={e=>setOrder(e.target.value)} className="w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="1, 3, 2, 4"/><p className="text-xs text-slate-500">Enter every page you want to keep, exactly once, in the desired order. Deleted pages should be omitted.</p><button onClick={()=>setOrder(Array.from({length:count},(_,i)=>i+1).filter(n=>!deleted.includes(n)).join(', '))} className="text-xs font-semibold text-blue-600">Reset to original order</button></div>
 <div className="space-y-3"><h2 className="font-bold">Page actions</h2><div className="space-y-2">{Array.from({length:count},(_,i)=>i+1).map(n=><div key={n} className={`flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3 ${deleted.includes(n)?'border-red-200 bg-red-50 opacity-70':'border-slate-200 bg-white'}`}><div className="flex items-center gap-3"><div className="flex h-10 w-9 items-center justify-center rounded-lg bg-slate-100"><FileText size={18}/></div><div><div className="text-sm font-semibold">Page {n}</div><div className="text-xs text-slate-500">{deleted.includes(n)?'Marked for removal':`Rotation: ${rotations[n]||0}°`}</div></div></div><div className="flex items-center gap-2"><select aria-label={`Rotate page ${n}`} disabled={deleted.includes(n)} value={rotations[n]||0} onChange={e=>setRotations(p=>({...p,[n]:Number(e.target.value)}))} className="rounded-lg border p-2 text-xs"><option value={0}>0°</option><option value={90}>90°</option><option value={180}>180°</option><option value={270}>270°</option></select><button title="Rotate clockwise 90°" disabled={deleted.includes(n)} onClick={()=>setRotations(p=>({...p,[n]:((p[n]||0)+90)%360}))} className="rounded-lg border p-2 disabled:opacity-30"><RotateCw size={15}/></button><button title="Toggle page removal" onClick={()=>toggleDelete(n)} className={`rounded-lg border p-2 ${deleted.includes(n)?'border-red-300 text-red-600':'text-slate-500'}`}><Trash2 size={15}/></button></div></div>)}</div></div>
 <button onClick={process} disabled={loading||!file||count-deleted.length<1} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3.5 font-semibold text-white hover:bg-blue-700 disabled:opacity-50">{loading?<><Loader2 className="animate-spin" size={18}/> Processing…</>:<>Export Organized PDF <ArrowDown size={18}/></>}</button></>}
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <div className="border-t pt-4 text-sm text-slate-500">Need to combine multiple documents? <Link className="font-semibold text-blue-600 underline" to="/tools/merge-pdf">Open Merge PDF →</Link></div>
 </section></div></div>;
}
