import { ToolDefinition } from '../types';

export const TOOLS: ToolDefinition[] = [
  {
    id: 'pdf-to-docx',
    name: 'PDF to DOCX',
    description: 'Convert PDF files to editable Microsoft Word documents with accurate text layout formatting preservation.',
    shortDescription: 'Convert PDF to editable DOCX documents instantly.',
    category: 'convert',
    iconName: 'FileText',
    accepts: 'application/pdf',
    multiple: false,
    maxSizeMB: 30,
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert structured PDF tables and text into a spreadsheet workbook for easier analysis and editing.',
    shortDescription: 'Turn table-based PDF content into Excel spreadsheets.',
    category: 'convert',
    iconName: 'FileSpreadsheet',
    accepts: 'application/pdf',
    multiple: false,
    maxSizeMB: 30,
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    description: 'Extract pages from a PDF and convert them into individual high-resolution PNG image files inside a structural ZIP folder.',
    shortDescription: 'Extract PDF pages into clean high-res PNG images.',
    category: 'convert',
    iconName: 'Image',
    accepts: 'application/pdf',
    multiple: false,
    maxSizeMB: 30,
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel workbooks into readable PDF documents while preserving sheet names, rows, and values.',
    shortDescription: 'Export spreadsheet data to a clean PDF document.',
    category: 'convert',
    iconName: 'FileSpreadsheet',
    accepts: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,.xlsx',
    multiple: false,
    maxSizeMB: 30,
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into a single document in any custom order. Organize and concatenate easily.',
    shortDescription: 'Combine multiple PDF documents into a single file.',
    category: 'organize',
    iconName: 'Layers',
    accepts: 'application/pdf',
    multiple: true,
    maxSizeMB: 50,
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Split a PDF document into individual page ranges or extract all pages as individual files with full page range selectors.',
    shortDescription: 'Split a PDF into multiple distinct files or ranges.',
    category: 'organize',
    iconName: 'Scissors',
    accepts: 'application/pdf',
    multiple: false,
    maxSizeMB: 30,
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert images (such as JPEG, PNG, WebP) into organized, standard PDF documents with optimized orientation alignment.',
    shortDescription: 'Transform PNG, JPG, or WebP images into PDFs.',
    category: 'convert',
    iconName: 'FileImage',
    accepts: 'image/png, image/jpeg, image/webp',
    multiple: true,
    maxSizeMB: 40,
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce the file size of your PDF while maintaining optimal image quality and document readability.',
    shortDescription: 'Shrink your PDF size without compromising quality.',
    category: 'optimize',
    iconName: 'Minimize2',
    accepts: 'application/pdf',
    multiple: false,
    maxSizeMB: 40,
  },

  {
    id: 'ai-pdf-summarizer',
    name: 'AI PDF Summarizer',
    description: 'Use AI to create a short overview, detailed summary, and key takeaways from PDF documents.',
    shortDescription: 'Summarize long PDFs with AI-generated insights.',
    category: 'ai',
    iconName: 'Brain',
    accepts: 'application/pdf',
    multiple: false,
    maxSizeMB: 50,
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Reorder, rotate, and remove individual PDF pages, then export your organized document.',
    shortDescription: 'Rearrange, rotate, or remove PDF pages.',
    category: 'organize',
    iconName: 'FileStack',
    accepts: 'application/pdf',
    multiple: false,
    maxSizeMB: 50,
  },
];
